server.port: 8083

logging:
  level:
    org.springframework:

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testDB/testdc
    username: sa
    password:

  ## AUTO-RESTART 사용 여부
  devtools:
    remote:
      restart:
        enabled: false

  ## 다국어 메시지 설정 Resource Bundle
  messages:
    basename: messages
  ## JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    ## SQL 이쁘게 출력
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  sql:
    init:
      mode: always

  security:
    user:
      name: user
      password: password
      roles: USER


## Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"


