server.port: 8082

logging:
  level:
    org.springframework:

spring:
  ## 다국어 메시지 설정 Resource Bundle
  messages:
    basename: messages
  ## JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
    

## Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

